copyright: (c) 2019 Torben Soennecken. All rights reserved
theme: readthedocs
site_name: configuration-substitution
site_author: Torben Soennecken
edit_uri: edit/master/docs/
pages:
  Functions:
    ConvertTo-NamingArray: functions\ConvertTo-NamingArray.md
    ConvertTo-NamingDictionary: functions\ConvertTo-NamingDictionary.md
  Usage: usage.md
  Home: index.md
